### PR TITLE
Aoflagger does not load because of missing libraries

### PR DESCRIPTION
**Pull request by aroffringa**

### CODE REVIEW

**Comment by aroffringa** [comment]
@tammojan would you like to fix Travis-CI ? Seems it misses some libs.

**Comment by tammojan** [comment]
Was boost-signals really necessary?

**Comment by aroffringa** [comment]
I use it in aoflagger... don't think it is trivial to remove

**Comment by tammojan** [comment]
Ok, I'll fix travis.

**Pull request merged**
