### PR TITLE
Replace asserts with throw std::runtime_error when appropriate

### PR DESCRIPTION
**Pull request by aroffringa**
Pull request to finish #1. I think the rule should be that any error caused by bad input
(parset error, command line error, data format error, etc) should throw an exception.
Any check on internal consistency or logic can be an assert(), so that they are disabled when
building in RELEASE mode. Some of the e.g. parset errors are now checked with 'assert',
which means that they won't be checked when build in RELEASE mode. Moreover, an assert
error is not very helpful for the user, an exception is at least a slightly friendlier
description of the problem.

### CODE REVIEW

**Comment by tammojan** [comment]
Thanks, this looks good. I would like to rephrase some of the error messages; are you still working on this branch or could I fix it on this branch?

**Comment by aroffringa** [comment]
I'm all in favour of rephrasing error messages :). I had done a few more changes ; I'll commit and push these to this branch and then stay off. I decided not to involve the demixing code, since they sprinkled with asserts that I don't fully understand, plus I'm not sure how alive that code is anyway...

**Comment by aroffringa** [comment]
Oh crap, I committed something that doesn't compile; will you fix that too @tammojan ?

**Comment by tammojan** [comment]
> Oh crap, I committed something that doesn't compile; will you fix that too @tammojan ?

I was about to find out :) Sure, fixed now.

**Comment by tammojan** [comment]
@aroffringa Back to you; could you merge if it's ok with you?

**Comment by aroffringa** [comment]
I had not yet gone through all the files ; shall I first do that and then merge everything at once?

**Comment by tammojan** [comment]
Fine with me; I'll stay off the branch for now.

**Comment by aroffringa** [comment]
@tammojan commit is finished now, ready to merge?

Fixes #1 .

**Pull request merged**
