### PR TITLE
Add additional options helpful for LBA calibration

### PR DESCRIPTION
**Pull request by darafferty**
I added a few things to DDECal to address some issues @revoltek found with calibration of LBA data (issues #81 and #99):

- add option to restrict propagation to converged solutions only ("propagateconvergedonly")
- add option to flag unconverged solutions ("flagunconverged")
- add an amplitude-divergence check to the rotation+diagonal constraint, as station amplitudes occasionally diverge (some with very high values, some with very low ones) in this mode. The check ensures amplitudes drift by no more than a factor of 5 from the mean over all stations
- add option to flag solutions if this amplitude divergence happens and the solver does not converge ("flagunconverged" + "flagdivergedonly"). All stations will be flagged if any one station is detected to diverge

### CODE REVIEW

**Comment by revoltek** [comment]
I checked these options they seem to work as expected for me.

**Comment by aroffringa** [comment]
I went through the code changes and it looks good to me. Thanks a lot @darafferty , seems this is very useful!

**Comment by aroffringa** [comment]
@darafferty Btw, have you updated the DPPP doc at https://www.astron.nl/lofarwiki/doku.php?id=public:user_software:documentation:ndppp#ddecal with the new options ?

**Comment by darafferty** [comment]
Ah, no -- thanks for reminding me. I'll do it now.

**Pull request merged**
